// Action Types for Redux
export const NAVBAR_ACTIONS = {
  FETCH_NAVBAR_DATA_REQUEST: 'FETCH_NAVBAR_DATA_REQUEST',
  FETCH_NAVBAR_DATA_SUCCESS: 'FETCH_NAVBAR_DATA_SUCCESS',
  FETCH_NAVBAR_DATA_FAILURE: 'FETCH_NAVBAR_DATA_FAILURE',
};

// You can add more action types here as your app grows
export const USER_ACTIONS = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGOUT: 'LOGOUT',
};

export const CART_ACTIONS = {
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  UPDATE_QUANTITY: 'UPDATE_QUANTITY',
  CLEAR_CART: 'CLEAR_CART',
};

export const PRODUCT_ACTIONS = {
  FETCH_PRODUCTS_REQUEST: 'FETCH_PRODUCTS_REQUEST',
  FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
  FETCH_PRODUCTS_FAILURE: 'FETCH_PRODUCTS_FAILURE',
  FETCH_PRODUCT_DETAILS_REQUEST: 'FETCH_PRODUCT_DETAILS_REQUEST',
  FETCH_PRODUCT_DETAILS_SUCCESS: 'FETCH_PRODUCT_DETAILS_SUCCESS',
  FETCH_PRODUCT_DETAILS_FAILURE: 'FETCH_PRODUCT_DETAILS_FAILURE',
};
